const config = require('../config');
const { createDiskStorage } = require('./disk');

// The one place the app touches file storage. Keys are paths like "avatars/12-a1b2.webp",
// always generated by us. Swapping disk for S3 means adding a driver here and nothing else.
const drivers = { disk: createDiskStorage };
const driver = drivers[config.storage.driver](config.storage);

module.exports = {
  put: (key, buffer) => driver.put(key, buffer),
  remove: (key) => driver.remove(key),
  // The public URL for a stored key, or null when there's nothing stored.
  urlFor: (key) => (key ? driver.urlFor(key) : null),
};
